# File: grpc-td-helloworld.yaml
#
# This corrected file uses the proper API versions for the GKE Gateway API
# resources and explicitly specifies the 'default' namespace for all objects.

---
# 1. Deployment for the gRPC server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: default
  labels:
    run: app1
spec:
  selector:
    matchLabels:
      run: app1
  replicas: 2
  template:
    metadata:
      labels:
        run: app1
    spec:
      containers:
      - image: grpc/java-example-hostname:1.50.2
        name: app1
        ports:
        - protocol: TCP
          containerPort: 50051

---
# 2. Service that creates the Network Endpoint Group (NEG)
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: default
  annotations:
    # This annotation creates a standalone NEG.
    cloud.google.com/neg: '{"exposed_ports":{"8080":{"name": "example-grpc-server"}}}'
spec:
  ports:
  - port: 8080
    name: helloworld
    protocol: TCP
    targetPort: 50051
  selector:
    run: app1
  type: ClusterIP

---
# 3. GcpGateway for the regional external load balancer
apiVersion: networking.gke.io/v1beta1
kind: GcpGateway
metadata:
  name: helloworld-gateway
  namespace: default
spec:
  gatewayType: REGIONAL_EXTERNAL_MANAGED
  ports:
  - port: 443

---
# 4. GRPCRoute to define the routing from the Gateway to the BackendService
apiVersion: networking.k8s.io/v1beta1
kind: GRPCRoute
metadata:
  name: helloworld-grpc-route
  namespace: default
spec:
  parentRefs:
  - name: helloworld-gateway
    namespace: default # Important: reference the gateway in the same namespace
  hostnames:
  - "your-domain.com" # Replace with your actual domain
  rules:
  - backendRefs:
    - name: helloworld-grpc-backend-service
      port: 8080

---
# 5. Backend Service for the gRPC load balancer
apiVersion: networking.gke.io/v1beta1
kind: BackendService
metadata:
  name: helloworld-grpc-backend-service
  namespace: default
spec:
  backends:
  - neg: helloworld-service
  healthCheck: helloworld-grpc-health-check
  loadBalancingScheme: EXTERNAL_MANAGED
  protocol: GRPC
  timeoutSec: 30

---
# 6. Health Check for the gRPC service
apiVersion: networking.gke.io/v1beta1
kind: HealthCheck
metadata:
  name: helloworld-grpc-health-check
  namespace: default
spec:
  checkIntervalSec: 5
  timeoutSec: 5
  healthyThreshold: 2
  unhealthyThreshold: 10
  grpcHealthCheck:
    port: 50051
