---
# service.yaml (Simplified)
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  ports:
  - port: 8080
    name: helloworld
    protocol: TCP
    targetPort: 50051
  selector:
    run: app1
  type: NodePort
---
# ingress.yaml (Simplified)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress
  annotations:
    kubernetes.io/ingress.class: "gce-regional-ingress"
spec:
  rules:
  - host: helloworld.gcpcloudtest.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helloworld
            port:
              number: 8080
